apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: media-stack
data:
  settings.yaml: |
    title: HomeLab Dashboard
    base: https://dashboard.sigtom.dev

  bookmarks.yaml: |
    - Media:
        - GitHub:
            - icon: github.png
              href: https://github.com/

  proxmox.yaml: |
    # Empty Proxmox Config

  custom.css: |
    /* Custom CSS */

  custom.js: |
    /* Custom JS */

  services.yaml: |
    - Media:
        - Plex:
            icon: plex.png
            href: https://plex.sigtom.dev
        - Overseerr:
            icon: overseerr.png
            href: https://overseerr.sigtom.dev
        - Riven:
            icon: riven.png
            href: https://riven.sigtom.dev

    - Management:
        - Sonarr:
            icon: sonarr.png
            href: https://sonarr.sigtom.dev
        - Radarr:
            icon: radarr.png
            href: https://radarr.sigtom.dev
        - Sabnzbd:
            icon: sabnzbd.png
            href: https://sabnzbd.sigtom.dev
        - Prowlarr:
            icon: prowlarr.png
            href: https://prowlarr.sigtom.dev
        - Bazarr:
            icon: bazarr.png
            href: https://bazarr.sigtom.dev
        - RDT-Client:
            icon: rdtclient.png
            href: https://rdt-client.sigtom.dev

    - Infrastructure:
        - Apprise:
            icon: apprise.png
            href: https://apprise.sigtom.dev
        - ArgoCD:
            icon: argocd.png
            href: https://argocd.sigtom.dev
        - OpenShift:
            icon: openshift.png
            href: https://console-openshift-console.apps.ossus.sigtomtech.com/

  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /media
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short

  kubernetes.yaml: ""
  docker.yaml: ""
