apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailrise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailrise
  template:
    metadata:
      labels:
        app: mailrise
    spec:
      containers:
      - name: mailrise
        image: docker.io/sandipb/mailrise:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: PYTHONPATH
          value: /home/mailrise/.local/lib/python3.12/site-packages
        volumeMounts:
        - name: mailrise-config
          mountPath: /etc/mailrise.conf
          subPath: mailrise.conf
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: mailrise-config
        secret:
          secretName: mailrise-config