apiVersion: v1
kind: Service
metadata:
  name: mailrise
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.16.100.211
spec:
  type: LoadBalancer
  selector:
    app: mailrise
  ports:
  - protocol: TCP
    port: 8025
    targetPort: 8025