apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pool.yaml
  - metallb-instance.yaml
  - token-secret.yaml
  - speaker-monitor.yaml
  - controller-monitor.yaml
  - metrics-rbac.yaml
