apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: media-stack
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-prod
spec:
  rules:
  - host: plex.sigtom.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex-service
            port:
              name: pms
  tls:
  - hosts:
    - plex.sigtom.dev
    secretName: plex-tls
