apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: media-stack
  annotations:
    metallb.universe.tf/address-pool: machine-pool
spec:
  selector:
    app: plex
  ports:
    - name: pms
      port: 32400
      targetPort: 32400
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
  externalTrafficPolicy: Local
