apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: media-stack
  annotations:
    metallb.universe.tf/address-pool: machine-pool
spec:
  selector:
    app: plex
  ports:
    - name: pms
      port: 32400
      targetPort: 32400
  type: LoadBalancer
  externalTrafficPolicy: Local