apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sigtom/wow-ocp.git
    targetRevision: HEAD
    path: apps/aap-config/base
  destination:
    server: https://kubernetes.default.svc
    namespace: ansible-automation-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
