apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - rbac.yaml
  - secrets.yaml
  - limitrange.yaml
  - networkpolicy.yaml
  - pvc-media-library.yaml
  - zone1-deployments.yaml