---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-zurg-config
  namespace: media-stack
spec:
  encryptedData:
    rclone.conf: AgCnOIZiGo/gDw1Du34q3vynZtgqMoiJSYWo3jHD3zIB6OVPGvFZbjflhsc7d2G39LvIInmDqZtvTdcjkGseK1AqEO7KVkmTR1q2uQqaU5z7bWJOQTGd4pOSyNkrbAoRCjvogWQwobKRhty6Tn//xgXuOhZYL3ZNobxjnzP3RjalZ+N8UdCDVwJgc58woxjt4gYkf3n7qAjEc8aGPraB/MK5e/V+HlfAsABWZzDBHQxgyajN5fzJSk1fYQUf/8vDcO+qJ3nPaevfUODJO3ZKr2m9KpEiBmZTj+CY1+zFIMG6WwCHJ+PRNoOgT+Fikw1OXCSte15m22oIm0dSNcVFjHnp5kL3du7E4ipVfzGr+51WdNQbDboRpBOZmNW023TMPLKAiFxdbSrtz1jPP9GKFamBMoWbdJHpk/3VQBdsLIp8AuaLCe0Y8e/p31MRZjk4CYHUOI6QBKbWuqwvrFe5yDLs7NRBJkAB8Q3zNDdGf9qJW/T5Xv27yaqdJ+sO8oL4sVqgUNM8Y3PTCxQaRk36c9JxLBnxQRgZ6CdcxZiAGY5Cjqh3PR0SCpqT6My4YxXBCwEXgZ808PoVlZRzVcErmZad1a0ardZ1s2rhakMdAU9AB/JgU2fXRMaKbtrJHhlf07lYA/VRAhtV2bqZa/lrptK0shFGMHvR96sZcm8sA5Iaco/7cx1tNPRq+PveR1LKzNw2tL896EDDqs652ZJ71Bp455tZmmHzxUWiAB6S5Eej0ioHaApWANKPB3lkRXqK3S/l8nOjJ6aaMHwt7ERBYjM=
  template:
    metadata:
      name: rclone-zurg-config
      namespace: media-stack
