---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: media-stack
spec:
  encryptedData:
    rclone.conf: AgCkrRo6IlTy72lvKPgHrHIFwSSI/+fdCX1b1Gv4t47FSQpI29I+Ne7qjSW/pqn7lQ45Kg/dFd0qFlfR15xOQhiYNpoM28oMWO4qEzPPBnKi0XBHE5rJDzK5Usckp4yARJt6BG7Z1hqKcIA+kfKF90XRkw0gomZvGPLPGLrZBsTNV1lxocP6JGqwaz1RMRVIa+uB49Z1b6j0xadcjWHdFPBFWNivGmvln4vVHhukzBombl0pTvLdjt99F8bHNPIhk7TQCHnOgtDHbaQ942abmySdhJoymkdakPYBayC+8m2nnH35w0/MyEyOmDeh06iurK4iywstc9sqbpO2ZqvPfSwf6NSHnZ/KYgXBK/rrvh3XYQXqo9vZswPob+tFR8DuQzlto5ZO6kAWxt2JmVBfwkUSkbivh8SopmVTGWDTULPnRLHRzXkrA/I5DPpaOlNFk/sFI/ibw9cIAyX9FJ4+U9ET+VPfRtpSdw0VNOSec7QK5wvI5GK2RzK8Ti/vuFXxViuNFsTMxO3wC3YVr9QkgCeyH6a0u+4E4gbpARpTsov2kbp9sc+8bF0r5/vgQ5euusmOMSyCh3qPH4sD9k/UHki7Eof7uvsN+Bi7rtuHUAPEOKV3QiByMoQ3FDUi/XW6P/Zimz7lxvr1+l+n/KpZLANNIiSkU8XbDaCajTuJx4YNs5tZvSoF+Xhz+kJ5zHrWLBk3FZFclztTfDTpFsWTwA1v2tx1AdieQj8Z5942v9/19fx5IsHew2dqw5xxWLJH4N21C2V4SAq1SSZ0DTVnqUa/NErEzOL9ywG9/wM5HFyoiu8M9KNfkpfmnbLP3uSHniXDQLMGlfl/IUAhYD+RiLmfmfy17TxZE+cJRKBB/s5r8mijBZfypb21OuoCTp9CUdmHGRzVSsspslEWGMqpMq3wnJhJheg8
  template:
    metadata:
      name: rclone-config
      namespace: media-stack
