---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: media-stack
spec:
  encryptedData:
    rclone.conf: AgCiKGEHDpyT4BlNbBDEwdeALamEy2obvSVrXghkeIFZbroQZ9fzlFBrPoQeWcygyauSoFgzSeQjQqlgWJkt2lN8CNNBIgBoXeXnZthLN0jdxArouQ1X5w8av7qZcqeXPrRPfqj/Y9CSH5jqhrD7dDZZQ3y0wgYnq2kTsyqmQTiG+pbAKMvia2413Y6aaw/Ai2DHfQqakzfvxUZPBMZixN1wgjxhC/TAF8ca39wkMckC/+2Lp4hG/0g60X+jsKUNqzWrSpRfXYioakfn720MgcoSliNwek+kq9qi7UPQ9aaWt5UeqkCH6gEXpTgDy1YsJojXx+bHzNsC25ggysnYqJerNY6hzYjwgidlFPdGlg0Bc775q0x+/XYZeuZCSglkh3qDo51/s8O83cqjLOz44w+skAPXYNwuCylCirOgb2Ygk8vPk79jBee/cIjGZmACfBAOp0S9okEswH/pScmAyD1GTNl2amqBiwTLM33IIGc65J73fgXYZiZ9MNt7mZXdF3XY0QIc9xqbMF1RSPzgjoNFWbhgTGrdroh/H0Y96lVcOCyvhmZCIqW3YMckyYr4LoySoIuy4mIXVa7vr91ysuQ3r6/Hn4zOC23vLej4IFS+sSpXjAycPhTvPGYEUswrnYSX0rBNcNEB6gE6Nr/m7Xs92k4mwUq2NrgLwLeftzqGUz2T6/FKu98Lec6SWKNypuIgI6bGrWo7gpjgLSb4CrBErE5WTpoRJuKm+bcRmJsGOPi2FTGy+YT9Q31y2IjeM7bczbjNNUBuVQZgr7M/CEPuMxo1KBg37RhAExW2Hob3/5DAF791nOPnYfNy5e7Tbc7RwH1QQ6LF0yM0zRr+BPcYCKyDghdWheTghBmfuVRlfsY5MKWC50VyEvwHjZ9R+77iCi1c6wdWONdl5K71isNzd73h
  template:
    metadata:
      name: rclone-config
      namespace: media-stack
