---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: media-stack
spec:
  encryptedData:
    rclone.conf: AgCAMcAKomLp9pLDruXmIPbuZfh6YIdhrFjj/wNbaDcPpcDZcui2jPm6mp+u3ZeM5CnNwqjreHDW57LpwWHaF4+W2FomL29OnXlRyu5mECD1CyF1VHrfQJ12ndfJesR0QiWfd+vBy7Gbrto1C6dTHpEP0/N53i0b5NtjHHTH0ftGS+FApbsW2mduhEPf+8Bht5p2+aBi9sG0ds2mOcBaOdVBHnWHbz7EmuKR8GT0mnjBKYriBHFoKxjPZgW3yi1UIMUoNnckPiRCHaFduKcJO/TL7ghS8cySX7zryeTytDdFabY0DQTje/uduCIV75SgMD2elGyK19YgKfAdZcVZyPuSYVShSPYDxUljUmj5/f+jjoNPtf+mzZxfb13v2BgfPiVcE9BQy9S/sUy0klLwRgKHZB0N5viD5zHGgaRf/FL4coMoMiDhekMaB5pt3ZfH6OSCtzur0Z2wQG83g5GwOm5w/cNItx0XFWNYLrtYCoBjGoqJ8FjO+PrA2XXZzUjh2/xLNCjYKCInq8LvWMKwg9TJPqt+Wdy64wGtmJKHPiYGq4tNl/NaFhCIUVxEo6qDPvyzCD3MDC6QVS9/VjZ2SL7BawiSCgZ0hMeUoPScAZhAWxWdNgWTIimJe9ioMiSYZDOL/kuTU8Et7iKY7KS7PqVu2t4Zz5rHDbKT6FvuRltO5lKLEgqVDQcbV3Udafb+lGc664VArKVDyyNxY/lG9U+q4QpXDDIKeWB1a4UrnNIV1AzSxMXTga1ITFFfJsR8oGhEI1x8GYRrnRkGzF4M7Pss5DLHGXIFzDv7fjyVKX2Prm7fShnKLEDRMrrsQv+WgzhwaJaJHrnO6SrHVBgPJtvT16ICV4WWYn/wv58buPnNuUypxhGhKyjXMP5fOQ4hSUdQV4yGVhyl
  template:
    metadata:
      name: rclone-config
      namespace: media-stack
