apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- operatorgroup.yaml
- subscription-logging.yaml
- subscription-loki.yaml
- rbac.yaml
- loki-minio-secret.yaml
- lokistack.yaml
