apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - htpasswd-sealed-secret.yaml
  - cluster-oauth.yaml
  - admin-rbac.yaml
  - onelogin-rbac.yaml
  - onelogin-sealed-secret.yaml
