apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnbmFtZXNwYWNlJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJlY2VpdmVyOiAnc2xhY2snCiAgcm91dGVzOgogIC0gbWF0Y2hlcnM6CiAgICAtIGFsZXJ0bmFtZSA9IFdhdGNoZG9nCiAgICByZWNlaXZlcjogJ1dhdGNoZG9nJwpyZWNlaXZlcnM6Ci0gbmFtZTogJ0RlZmF1bHQnCi0gbmFtZTogJ1dhdGNoZG9nJwotIG5hbWU6ICdDcml0aWNhbCcKLSBuYW1lOiAnc2xhY2snCiAgc2xhY2tfY29uZmlnczoKICAtIGFwaV91cmxfZmlsZTogL2V0Yy9hbGVydG1hbmFnZXIvc2VjcmV0cy9zbGFjay13ZWJob29rL3VybAogICAgY2hhbm5lbDogJyNvY3AtYWxlcnRzJwogICAgc2VuZF9yZXNvbHZlZDogdHJ1ZQogICAgdGl0bGU6ICd7eyByYW5nZSAuQWxlcnRzIH19e3sgLkFubm90YXRpb25zLnN1bW1hcnkgfX1cbnt7IGVuZCB9fScKICAgIHRleHQ6ICd7eyByYW5nZSAuQWxlcnRzIH19e3sgLkFubm90YXRpb25zLmRlc2NyaXB0aW9uIH19XG57eyBlbmQgfX0nCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: openshift-monitoring
