apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnbmFtZXNwYWNlJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJlY2VpdmVyOiAnRGVmYXVsdCcKICByb3V0ZXM6CiAgLSBtYXRjaGVyczoKICAgIC0gYWxlcnRuYW1lID0gV2F0Y2hkb2cKICAgIHJlY2VpdmVyOiAnV2F0Y2hkb2cnCnJlY2VpdmVyczoKLSBuYW1lOiAnRGVmYXVsdCcKLSBuYW1lOiAnV2F0Y2hkb2cnCi0gbmFtZTogJ0NyaXRpY2FsJwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: openshift-monitoring
