apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprise-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apprise-api
  template:
    metadata:
      labels:
        app: apprise-api
    spec:
      containers:
      - name: apprise-api
        image: ghcr.io/caronc/apprise:latest
        env:
        - name: APPRISE_WORKER_COUNT
          value: "2"
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: apprise-config
          mountPath: /config/apprise.yml
          subPath: apprise.yml
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 6
      volumes:
      - name: apprise-config
        secret:
          secretName: apprise-config
