apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - external-secret.yaml
  - external-secret-dumb.yaml
  - external-secret-dumb-fields.yaml
  - external-secret-arrs.yaml
  - platform.yaml
