apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator.yaml
  - certificate.yaml
  - sidekick.yaml
  - bitwarden-api-creds-sealed.yaml
  - cluster-secret-store.yaml
# We'll add cluster-secret-store.yaml in the next step once the operator is up
