apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator.yaml
  - certificate.yaml
  - sidekick.yaml
  - bitwarden-api-creds-sealed.yaml

# Ensure everything is forced into our namespace
namespace: external-secrets
