apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nautobot

resources:
  - 00-namespace.yaml
  - sealed-secrets.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - nautobot-deployment.yaml
  - celery-worker-deployment.yaml
  - celery-beat-deployment.yaml
  - route.yaml
  - init-job.yaml
